import 'primereact/resources/themes/tailwind-light/theme.css'
import 'primereact/resources/primereact.min.css'
import 'primeicons/primeicons.css'
import './globals.scss'
import { Heebo } from 'next/font/google'

const heebo = Heebo({ subsets: ['latin'] })

export const metadata = {
  title: 'TwinBusiness',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <head>
        <link id="theme-link" rel="stylesheet" href="/themes/tailwind-light/theme.css" />
      </head>
      <body className={heebo.className}>{children}</body>
    </html>
  )
}
